name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get All Changed Markdown Files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v45
        with:
          safe_output: false
          # Avoid using single or double quotes for multiline patterns
          separator: "\n"
          files: |
            docs/zh/**.md
      - name: List All Changed Markdown Files
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
        run: |
          IFS="\n"
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
          unset IFS
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Call bin/main
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
        run: |
          node bin/main.js